buildscript {
	ext {
		cleanArchitectureVersion = '4.5.0'
		springBootVersion = '4.1.0'
		sonarVersion = '7.3.1.8318'
		jacocoVersion = '0.8.15'
		blockHoundVersion = '1.0.17.RELEASE'
	}
}

plugins {
	id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
	id 'org.springframework.boot' version "${springBootVersion}" apply false
	id 'org.sonarqube' version "${sonarVersion}"
	id 'jacoco'
}

sonar {
    def mergedReportPath = rootProject.layout.buildDirectory.file('reports/jacocoMergedReport/jacocoMergedReport.xml').get().asFile
    properties {
        property 'sonar.sourceEncoding', 'UTF-8'
        property 'sonar.exclusions', '**/MainApplication.java, **/config/**'
        property 'sonar.coverage.exclusions', '**/MainApplication.java, **/config/**, **/model/**, **/dto/**'
        property 'sonar.coverage.jacoco.xmlReportPaths', mergedReportPath
    }
}

apply from: './main.gradle'

tasks.sonar.dependsOn jacocoMergedReport
