databaseChangeLog:
  - changeSet:
      id: create-table-user-roles
      author: compira
      changes:
        - createTable:
            tableName: user_roles
            columns:
              - column:
                  name: user_id
                  type: UUID
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_user_roles
              - column:
                  name: role_id
                  type: UUID
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_user_roles
              - column:
                  name: created_at
                  type: TIMESTAMPTZ
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            constraintName: fk_user_roles_user
            baseTableName: user_roles
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            onDelete: CASCADE
        - addForeignKeyConstraint:
            constraintName: fk_user_roles_role
            baseTableName: user_roles
            baseColumnNames: role_id
            referencedTableName: roles
            referencedColumnNames: id
            onDelete: CASCADE
