server:
  port: 8080
spring:
  application:
    name: "compira-back"
  devtools:
    add-properties: false
  profiles:
    include: null
springdoc:
  swagger-ui.path: "/v3/swagger-ui.html"
  api-docs.path: "/v3/api-docs"
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:compira}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  cognito:
    region: ${COGNITO_REGION:us-east-1}
    user-pool-id: ${COGNITO_USER_POOL_ID:compira-dev-user-pool-id}
    client-id: ${COGNITO_CLIENT_ID:compira-dev-client-id}
cors:
  allowed-origins: "http://localhost:5173,http://localhost:8080"
